---
title: "Visualización de Datos"
subtitle: "Cosas a tener en cuenta"
description: De seguro te habrás preguntado de que va todo esto de la visualización de datos y si es necesario aprender algún lenguaje de programación y cuál sería el más apropiado para comenzar. Pero aún hay algunas cosas que debes tener en cuenta antes de emprender ese viaje.
author: EMTincopa
published: true
image: ""
date: 2018-12-27T00:58:19-05:00
draft: true
categories: ["Tips"]
tags: ["DataViz", "Data", "Power BI", "Tableau","R","Plot", "Tools"]
showtoc: false
---

# Un vistazo

Hola! 
De seguro te habrás preguntado de que va todo esto de la visualización de datos y si es necesario aprender algún lenguaje de programación y cuál sería el más apropiado para comenzar. En mi experiencia puedo decirte que lenguajes de programación para visualizar datos hay varios, siendo R el que yo utilizo hasta el momento. Pero veamos algunas cosas que debes tener en cuenta sobre la visualización de datos y otras opciones a las que podrías recurrir.

**LA VISUALIZACIÓN DE DATOS**

La visualización de datos se expresa como cualquier esfuerzo, en términos generales, para ayudar a las personas a comprender la información almacenada en grandes volúmenes de datos, que pueden parecer inabarcables. Para lograr esto, tienes que mirar tus datos. Unos gráficos iniciales y tablas te permiten explorar y conocer la estructura de la información recopilada, en otras palabras, puedes extraer significados de tu propia información.

Desde mi punto de vista no creo que haya buenas o malas visualizaciones, pero sí mejores o peores según el tipo de información con la cual se esté trabajando. Las visualizaciones acertadas facilitan la comunicación de tus ideas y hallazgos a otras personas. Al mismo tiempo, producir gráficos efectivos a partir de tus propios datos es la mejor manera de desarrollar un buen ojo crítico para no solo tus gráficos sino también los de los demás, como los que encuentras en los periódicos, páginas web, artículos de investigación, slides de negocios, etc.

**¿POR QUÉ LA VISUALIZACIÓN DE DATOS ES IMPORTANTE EN CUALQUIER ÁREA?**

En realidad, es difícil imaginar que un profesional científico o industrial no se beneficie de hacer la data más entendible para apoyar sus conclusiones y tomar mejores decisiones.

Con el crecimiento de la tecnología han aparecido nuevas herramientas que facilitan la creación de gráficos interactivos e infografías de alto impacto, pero estas nuevas herramientas necesitan de profesionales que comprendan y manejen de la mejor forma los elementos visuales (tablas, gráficos y mapas) para la representación gráfica de información y datos. Y en cierto punto, crear gráficos de barras o gráficos circulares más sofisticados que los encontrados en las hojas de cálculo de Microsoft Excel, pero siempre primando el lograr transmitir un mensaje claro de lo que nos quieren decir nuestros datos.

Si nos centramos en el mundo de los negocios, encontramos que la visualización de datos es de hecho la principal herramienta de la inteligencia de negocios (BI), ayudando a democratizar los datos y los análisis, y ponerlos a disposición de las distintas unidades funcionales de una empresa. Las nuevas herramientas que han salido al mercado (Tableu, Qlik, y Power BI), por lo general, son más fáciles de operar que el software de análisis estadístico tradicional o programas pioneros en el BI. Esto ha llevado al aumento de empresas implementando por su cuenta estas herramientas enfocadas en la visualización de datos en sus organizaciones.

**PRIMEROS PASOS EN LA VISUALIZACIÓN DE DATOS**

Lo que puedo decir en este momento es que R es el lenguaje de programación perfecto para perderle el miedo al código y dar tus primeros pasos en la ciencia de datos y la visualización. Pero cuidado, antes de aprender a manipular los datos, tienes que aprender a visualizarlos (La visualización de datos es una relación cíclica entre manipular y visualizar datos, entre otras cosas).

Por otra parte, deberías vivir Microsoft Excel al máximo, llegar a manejar bien las tablas dinámicas y tantear hasta donde puedes llegar, y cuando sientas las limitaciones de esa herramienta, aventúrate a buscar otras, pero si no tienes problemas en tu trabajo y Excel te da todo lo que necesitas, entonces deberías pensar muy bien si en verdad quieres adentrarte en el mundo de los datos y la visualización (En serio, con Microsoft Excel se pueden hacer muchas cosas, y con algo más de esfuerzo gráficos bonitos). 

También, si eres de los que solo reciben los datos y necesitas una herramienta para explorarlos visualmente como también crear gráficos visualmente atractivos, Tableau sería una gran opción al ser muy popular y realmente poderoso. Tableau es una herramienta de escritorio que te permite crear visualizaciones creativas y dashboards para monitorear las métricas más importantes en tu negocio, y si eres alguien experimentado en el lenguaje de programación JavaScript puedes subir tus visualizaciones hechas en Tableau a un sitio web. Tiene una versión pública gratuita y otra de pago que puedes obtener de forma gratuita si acreditas que eres estudiante, los gráficos que desarrolles puedes subirlos a tus redes sociales, incluirlos en investigaciones, imprimirlos para posters, etc. 

Otra opción es Power BI, la cual es, desde mi punto de vista, la mejor herramienta para el análisis de negocios creada por Microsoft. Power BI te permite visualizar los datos de tu empresa, subirlos a una nube y compartirlos con todas las unidades funcionales de tu negocio, así como también descargar tus visualizaciones en formatos estáticos como los PDFs (Bueno, Tableau no es tan diferente en ese sentido) para editarlos a tu gusto con otras herramientas. Si eres un Excel boy creo que Power BI, a pesar de ser algo distinto, tiene un poco del mismo espíritu (Sobre todo cuando trabajes con la opción de tablas Fact y Dim). En resumen, Power BI te brinda una ventana donde podrás visualizar gráficos impactantes y crear Dashboards y reportes dinámicos. 

Regresando a R, primero que nada, es gratis, tiene un séquito gigantesco de desarrolladores que constantemente crean y agregan nuevos paquetes, puede manejar grandes volúmenes de datos, lo retroalimenta una comunidad muy activa, brinda una amplia gama de herramientas estadísticas y, hay grandes recursos gratuitos para aprenderlo, como es el caso de Coursera, DataCamp, Udemy, entre otros.  
Si tu matriz de datos en Excel te está dando problemas al ser muy grande, no es lo suficientemente flexible y las visualizaciones no son lo que esperas, R es la solución, siendo muy útil para explorar rápidamente tus datos y tener visualizaciones muy personalizadas.

Por desgracia, lograr visualizaciones tan grandiosas como las que podemos encontrar en los principales periódicos estadounidenses no es una tarea fácil y necesitarás mucha determinación y ganas para lograr que tus primeros trabajos tengan esos diseños de gran impacto. Tal vez tengas que aprender algo de Adobe Illustrator para retocar tus gráficos o crear infografías.

En cualquier caso, si finalmente te has decidido aprender R para sumergirte en la visualización de datos, te recomiendo que revises los paquetes ggplot2 y dplyr (si eres disciplinado podrás aprender la sintaxis de R en menos de un mes). Una vez aprendas la sintaxis, los gráficos de dispersión, barras y de burbujas, entre otros, serán muy fáciles. 

En general las visualizaciones que parecían extremadamente difíciles terminarán siendo más sencillas de lo que esperabas. A partir de ahí tienes que hacer explotar tu creatividad, domina ggplot2 y dplyr porque serán tus principales herramientas para más adelante encontrar historias entre tus datos.
